swagger: "2.0"

info:
  version: 1.0.0
  title: Sysworld Servicios S.A. API
  description: Public services offered by Sysworld

schemes:
  - https
host: api-staging.enviocertificado.com

paths:
  /login:
    post:
      summary: Obtain a JWT from a username/password (for web sessions)
      description: Useful when logging in from a web interface or other UI in order to open a session
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: Authorization
        in: header
        description: Use 'Basic' with your username and password
        required: true
        type: string
      - in: body
        name: EmptyRequest
        required: true
        schema:
          $ref: "#/definitions/Empty"
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/LoginResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Access-Control-Allow-Headers:
              type: string
        400:
          description: Client Error, Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        401:
          description: Not Authorized
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        405:
          description: Method Not Allowed
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        406:
          description: Not Acceptable
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        415:
          description: Unsupported Media Type
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        500:
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
  /validations/email:
    post:
      summary: Validates an email address
      description: This will attempt to validate an email address testing its consistency and other factors
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: Authorization
        in: header
        description: Use 'Basic' with 'apikey' as username and your api key as the password. Or 'Bearer' and your JWT.
        required: true
        type: string
      - in: body
        name: EmailValidationRequest
        required: true
        schema:
          $ref: "#/definitions/EmailValidationRequest"
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/ValidationResponse"
          headers:
            X-New-JWT:
              type: string
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Access-Control-Allow-Headers:
              type: string
        202:
          description: Only when content-type is text/csv. Your batch was accepted and will be eventually processed
          schema:
            $ref: "#/definitions/ValidationBatchResponse"
          headers:
            X-New-JWT:
              type: string
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Access-Control-Allow-Headers:
              type: string
        400:
          description: Client Error, Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-New-JWT:
              type: string
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        401:
          description: Not Authorized
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        405:
          description: Method Not Allowed
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        406:
          description: Not Acceptable
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        415:
          description: Unsupported Media Type
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        500:
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-New-JWT:
              type: string
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string

  /validations/batch/{id}:
    get:
      summary: Returns batch information or result
      description: "When requested with 'Accept: text/csv' will return the batch result. When requested with 'Accept: application/json' will return the information of the given batch id."
      consumes:
        - application/json
      produces:
        - application/json
        - text/csv
      parameters:
      - name: Authorization
        in: header
        description: Use 'Basic' with 'apikey' as username and your api key as the password. Or 'Bearer' and your JWT.
        required: true
        type: string
      #- name: Accept
      #  in: header
      #  description: "When requested with 'Accept: text/csv' will return the batch result. When requested with 'Accept: application/json' will return the information of the given batch id."
      #  required: true
      #  type: string
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: Successful operation
          examples:
            application/json:
              batch:
                id: 123
                type: "email_validation"
                request_id: "ba4d0af8-4a1c-11e7-829a-7831c1c0328a"
                state: "finished"
                error: "internal_error"
                error_line: 400
                rows_total: 500
                rows_processed: 400
                created: 1496684197
                updated: 1496684797
                created_str: "2017-06-05T17:36:37Z"
                updated_str: "2017-06-05T17:46:37Z"
              success: true
            text/csv:
              email;result;hint;custom_fields

              user1@domain.com;valid;uzer@domain.com;extra_field_1;extra_field_2

              user2@domain.com;invalid;;extra_field_1;extra_field_2

              user3@domain.com;unknown;;extra_field_1;extra_field_2
          schema:
            $ref: "#/definitions/BatchResponse"
          headers:
            X-New-JWT:
              type: string
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Access-Control-Allow-Headers:
              type: string
        400:
          description: Client Error, Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-New-JWT:
              type: string
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        401:
          description: Not Authorized
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        405:
          description: Method Not Allowed
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        406:
          description: Not Acceptable
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        415:
          description: Unsupported Media Type
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
        500:
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            X-New-JWT:
              type: string
            X-Request-ID:
              type: string
            X-Request-Time:
              type: integer
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Content-Type:
              type: string
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"

  ErrorResponse:
    type: object
    required:
    - success
    - error_description
    properties:
      success:
        type: boolean
        description: Always false on errors
      error_description:
        type: array
        description: One or more specific error messages for client errors
        items:
          type: string
    title: ErrorResponse
    description: This is an error response for requests with status other than 2xx

  EmailValidationRequest:
    type: object
    required:
    - email
    properties:
      email:
        type: string
        description: The email address to validate
    title: EmailValidationRequest
    description: Payload to validate email addresses

  EmailValidationResult:
    type: "string"
    title: "EmailValidationResult"
    description: "Possible result values for email validations"
    enum:
    - valid
    - invalid
    - unknown
    - retry_later

  LoginResponse:
    type: object
    required:
    - token
    properties:
      token:
        type: string
        description: A JWT
    title: LoginResponse
    description: Login Response

  ValidationBatchResponse:
    type: object
    required:
    - batch_id
    - success
    properties:
      batch_id:
        type: integer
        description: The batch ID
      success:
        type: boolean
        description: Result of the operation itself (can be true even if the object is not valid)
    title: ValidationBatchResponse
    description: Response for a validation batch creation

  BatchTypes:
    type: "string"
    title: "BatchTypes"
    description: "Possible batch types"
    enum:
    - email_validation

  BatchStates:
    type: "string"
    title: "BatchStates"
    description: "Possible batch states"
    enum:
    - pending
    - ready
    - validating
    - processing
    - exporting
    - failed
    - finished
  BatchErrors:
    type: "string"
    title: "BatchErrors"
    description: "Possible batch errors"
    enum:
    - internal_error
    - line_too_long

  Batch:
    type: object
    required:
    - id
    - type
    - request_id
    - state
    - error
    - error_line
    - rows_total
    - rows_processed
    - created
    - updated
    - created_str
    - updated_str
    properties:
      id:
        type: integer
        description: The Batch ID
      type:
        $ref: "#/definitions/BatchTypes"
      request_id:
        type: string
        description: The request ID that originated the batch
      state:
        $ref: "#/definitions/BatchStates"
      error:
        $ref: "#/definitions/BatchErrors"
      error_line:
        type: integer
        description: Number of line that caused an error in the batch
      rows_total:
        type: integer
        description: Total number of lines recogniced in the batch
      rows_processed:
        type: integer
        description: Total number of processed rows in the batch
      created:
        type: integer
        description: Unix timestamp of the batch creation
      updated:
        type: integer
        description: Unix timestamp for last batch update
      created_str:
        type: string
        description: ISO8601 date of the batch creation
      updated_str:
        type: string
        description: ISO8601 date of the last batch update
    title: Batch
    description: A batch

  BatchResponse:
    type: object
    required:
    - batch
    - success
    properties:
      batch:
        $ref: "#/definitions/Batch"
      success:
        type: boolean
        description: Result of the operation itself (can be true even if the object is not valid)
    title: BatchResponse
    description: Result of requesting a batch information

  ValidationResponse:
    type: object
    required:
    - id
    - result
    - success
    - last_step
    - extra
    properties:
      id:
        type: string
        description: The operation ID
      result:
        $ref: "#/definitions/EmailValidationResult"
      success:
        type: boolean
        description: Result of the operation itself (can be true even if the object is not valid)
      last_step:
        type: string
        description: Last step reached in the validation chain
      hint:
        type: string
        description: Suggestion when returning a result as invalid
      extra:
        type: array
        items:
          type: string
        description: "Extra information after validation, e.g: error descriptions"
    title: ValidationResponse
    description: Response of an email address validation
